name = "charni-pos"
compatibility_date = "2026-06-11"

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "charnipos-db"
database_id = "00000000-0000-0000-0000-000000000000"
